apiVersion: v1
kind: Service
metadata:
  name: xyzpoc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: xyzpoc
