apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xyzpoc-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service: 
            name: xyzpoc
            port: 
              number: 80
