name: "Docker publish"

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-image:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v3"
        with:
          username: "${{ secrets.DOCKER_USER }}"
          password: "${{ secrets.DOCKER_TOKEN }}"

      - name: "Build and push image tags"
        uses: "docker/build-push-action@v5"
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: |
            streetplaya/xyzpoc:${{ github.ref_name }}